export const languages = {
  en: {
    editions: "editions",
    controller: "controller",
    about: "about",
    explore: "explore",
    news: "news",
    faq: "faq",
    currentlang: "english",
    release: "Release",
    days: "D",
    hours: "H",
    minutes: "M",
    seconds: "S",
    hero: "God of War Ragnarök",
    text: "Taking place three years following the events of the previous game, Fimbulwinter, a great winter that spans three summers, is drawing to a close which will begin the prophesied Ragnarök.",
    buy: "buy now",
    editionstitle: "Editions",
    standard: "Standard Edition",
    offline: "Offline play enabled",
  },
  uk: {
    editions: "видання",
    controller: "контролер",
    about: "про нас",
    explore: "досліджувати",
    news: "новини",
    faq: "питання",
    currentlang: "Мова",
    release: "випускати",
    days: "Дні",
    hours: "Години",
    minutes: "Хвилини",
    seconds: "Секунди",
    hero: "Бог війни Рагнарек",
    text: "Розгортається через три роки після подій попередньої гри, Фімбулвінтер, велика зима, яка охоплює три літа, наближається до кінця, що почне передбачуваний Рагнарек.",
    buy: "Купити зараз",
    editionstitle: "Видання",
    standard: "Стандартне видання",
    offline: "Увімкнено офлайн-гра",
  },
};
